apiVersion: v1
kind: Service
metadata:
    name: "gowebtest-7f85"
    labels:
        app: "gowebtest-7f85"
spec:
    type: LoadBalancer
    ports:
    - port: 5775
      targetPort: 5775
      protocol: TCP
      name: http
    selector:
        app: "gowebtest-7f85"